### PR TITLE
Remove TikTok watermark

### PR DESCRIPTION
**Pull request by solithcy**
# Watermarks are no more!!

This update changes the download method from TikTokAPI to my own script that uses the SnapTik API.
As you can see, there's a new file, `snapTik.py`. This file sends a request to SnapTik's servers, and then deobfuscates the response to download the video without a watermark to disk.

### CODE REVIEW

**Comment by jontstaz** [comment]
Does this still need the cookie information? Because I think the master is bugged, I just get the following error every time:

```OSError:` [WinError 14001] The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail
[WinError 14001] The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail
exception occured downloading. waiting and retrying```

**Comment by solithcy** [comment]
Um I don't think that's to do with the cookies, but no.
The cookies seem to be redundant, and after removing them on my machine I was still able to use the script to download videos. The script itself doesn't even use the cookies that you specify (see [this commit](https://github.com/HA6Bots/TikTok-Compilation-Video-Generator/commit/96d94f771abbc1bdc52bc039dd166dffb6871332))

**Comment by HA6Bots** [comment]
Hi, thanks @RoseChilds for your work in getting the bot supported by another API.
Unfortunately, I've been quite busy lately so I won't have time to test the API rigorously enough 
to push it to main just yet - so instead I've pushed it to a new branch snaptik-api.

If it gets positive feedback we can think about merging it into main.

Thanks again.

**Comment by monstavisch** [comment]
Downloading Clip 1/10
Could not find download URL
Error downloading clip

:'(

**Pull request merged**
